#import "../BHRDAcceptance.h"
#import "../BHRDBuildInfo.h"
static NSUInteger Checks;
static void Check(BOOL condition,NSString *message) { Checks++; if (!condition) { NSLog(@"FAIL: %@",message); exit(1); } }
static NSDictionary *Item(NSString *key) {
    for (NSDictionary *item in BHRDAcceptanceItems()) if ([item[@"id"] isEqual:key]) return item;
    return nil;
}
static void Event(NSString *name,NSDictionary *fields) { BHRDAcceptanceObserveEvent(name,fields); BHRDAcceptanceFlush(); }
int main(void) { @autoreleasepool {
    NSDictionary *recent=BHRDAcceptanceSnapshot();
    Check([recent[@"mode"] isEqual:@"recent"],@"Implicit runtime evidence is labelled as recent observations, not an explicit acceptance session");
    for (NSDictionary *item in recent[@"items"]) Check([item[@"status"] isEqual:@"pending"],@"No static capability or launch is a proven user result");
    Event(@"hook_supported",@{@"status":@"success"});
    Check([BHRDAcceptanceSnapshot()[@"observationCount"] isEqual:@0],@"Capability checks never count as real acceptance observations");
    BHRDAcceptanceObserveLaunch(NO,YES);
    NSDictionary *session=BHRDAcceptanceBeginSession(); NSString *sessionID=session[@"sessionID"];
    Check([session[@"mode"] isEqual:@"session"] && [session[@"build"][@"version"] isEqual:BHRD_BUILD_VERSION],@"Explicit start records the exact build and a separate acceptance session");
    Check([session[@"environment"][@"appVersion"] isKindOfClass:NSString.class] && [session[@"environment"][@"appBuild"] isKindOfClass:NSString.class] && [session[@"environment"][@"os"] isEqual:NSProcessInfo.processInfo.operatingSystemVersionString],@"The session records only fixed app/build/OS environment fields from the running process");
    Check([session[@"launches"] count]==1,@"Session includes the currently observed boot safety state");
    Event(@"photo_save_start",@{@"source":@"original",@"url":@"https://secret.invalid/account",@"handle":@"private-user"});
    Check([Item(@"photo_save")[@"status"] isEqual:@"running"],@"Beginning photo saving cannot count as a completed save");
    Event(@"photo_save_fetch",@{@"bytes":@100,@"errorDomain":@"",@"errorCode":@0});
    Event(@"photo_save_prepare",@{@"valid":@YES,@"width":@1200,@"height":@800});
    Event(@"photo_save_authorization",@{@"status":@3});
    Check([Item(@"photo_permission")[@"status"] isEqual:@"success"] && [Item(@"photo_save")[@"status"] isEqual:@"running"],@"Permission success is independent of the still-incomplete Photos transaction");
    Event(@"photo_save_committed",@{@"bytes":@100});
    Check([Item(@"photo_save")[@"stage"] isEqual:@"photos_commit"],@"Submitting Photos changes only records an awaiting callback stage");
    Event(@"photo_save_result",@{@"success":@YES,@"committed":@YES,@"errorCode":@0});
    Check([Item(@"photo_save")[@"status"] isEqual:@"success"] && ![Item(@"photo_save")[@"manualConfirmed"] boolValue],@"Only actual Photos completion becomes system-confirmed success; image correctness is not automatically confirmed");
    Event(@"photo_save_start",@{});
    Event(@"photo_save_result",@{@"success":@NO,@"committed":@NO,@"errorDomain":@"com.caun.xsuixin.photo-save",@"errorCode":@4});
    Check([Item(@"photo_save")[@"status"] isEqual:@"success"] && [Item(@"photo_save")[@"lastOutcome"] isEqual:@"cancelled"] && [Item(@"photo_save")[@"successCount"] isEqual:@1],@"A later user cancellation preserves previous successful runtime evidence");
    Event(@"photo_save_result",@{@"success":@NO,@"errorDomain":@"com.caun.xsuixin.photo-save",@"errorCode":@3});
    Check([Item(@"photo_save")[@"status"] isEqual:@"unsupported"] && [Item(@"photo_save")[@"stage"] isEqual:@"permission_denied"],@"Denied permission is blocked support, not a misleading Photos transaction failure");
    Event(@"photo_save_result",@{@"success":@NO,@"errorDomain":@"PhotosError",@"errorCode":@-1,@"errorMessage":@"private-user https://secret.invalid"});
    Check([Item(@"photo_save")[@"status"] isEqual:@"failed"] && [Item(@"photo_save")[@"error"][@"code"] isEqual:@-1],@"Real system failure preserves only error domain and code for diagnosis");
    Event(@"recovery_invoked",@{@"source":@"paused_boot",@"presented":@YES});
    Check(![Item(@"recovery_gesture")[@"status"] isEqual:@"success"],@"Automatically opened recovery menu never proves the three-finger gesture worked");
    Event(@"recovery_invoked",@{@"source":@"three_finger",@"presented":@NO});
    Check([Item(@"recovery_gesture")[@"status"] isEqual:@"failed"],@"A gesture that cannot present the menu is a presentation failure");
    Event(@"recovery_invoked",@{@"source":@"three_finger",@"presented":@YES});
    Check([Item(@"recovery_gesture")[@"status"] isEqual:@"success"],@"Gesture and actual presentation together are runtime evidence");
    Event(@"recovery_invoked",@{@"source":@"paused_boot",@"presented":@YES});
    Check([Item(@"recovery_gesture")[@"status"] isEqual:@"success"],@"Automatic paused boot does not erase earlier genuine gesture success");
    Event(@"safety_pause_changed",@{@"paused":@YES,@"success":@YES});
    Check([Item(@"pause_restart")[@"status"] isEqual:@"running"],@"Writing a pause flag awaits actual restart confirmation");
    BHRDAcceptanceObserveLaunch(YES,NO); BHRDAcceptanceFlush();
    Check([Item(@"pause_restart")[@"status"] isEqual:@"running"],@"Duplicating a boot event within the same process cannot prove a restart");
    BHRDAcceptanceTestReload();
    Check([BHRDAcceptanceCurrentSessionIdentifier() isEqual:sessionID],@"Explicit acceptance state persists across processes within the same build");
    BHRDAcceptanceObserveLaunch(YES,NO); BHRDAcceptanceFlush();
    Check([Item(@"pause_restart")[@"status"] isEqual:@"success"],@"Next boot must independently verify disabled hooks and paused flag");
    Event(@"safety_pause_changed",@{@"paused":@NO,@"success":@YES});
    BHRDAcceptanceTestReload(); BHRDAcceptanceObserveLaunch(NO,YES); BHRDAcceptanceFlush();
    Check([Item(@"resume_restart")[@"status"] isEqual:@"success"],@"Resume is confirmed only by a later boot with enabled hooks");
    NSString *attempt=NSUUID.UUID.UUIDString;
    Event(@"repost_detail_navigation",@{@"result":@"native_row_selection",@"row":@"secret-post",@"attempt":attempt});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"running"],@"Native row selection is a request, not evidence of navigation completion");
    Event(@"repost_detail_visible",@{@"attempt":attempt,@"confirmed":@NO});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"pending"],@"Unmatched detail identity remains unverified even if a details page became visible");
    Event(@"repost_detail_confirmation_timeout",@{@"attempt":NSUUID.UUID.UUIDString});
    Check([Item(@"repost_detail")[@"stage"] isEqual:@"detail_identity_unavailable"],@"A stale timeout cannot change the current navigation attempt");
    Event(@"repost_detail_confirmation_timeout",@{@"attempt":attempt});
    Check([Item(@"repost_detail")[@"stage"] isEqual:@"confirmation_timeout"] && [Item(@"repost_detail")[@"status"] isEqual:@"pending"] && [Item(@"repost_detail")[@"attempts"] isEqual:@1],@"A confirmation timeout records missing evidence without inventing navigation failure or a second attempt");
    Event(@"repost_detail_visible",@{@"attempt":attempt,@"confirmed":@NO,@"result":@"detail_identity_mismatch"});
    Check([Item(@"repost_detail")[@"stage"] isEqual:@"detail_identity_mismatch"] && [Item(@"repost_detail")[@"status"] isEqual:@"failed"],@"An actually observed wrong post has a distinct identity-mismatch failure stage");
    Event(@"repost_detail_visible",@{@"attempt":attempt,@"confirmed":@YES});
    Check([Item(@"repost_detail")[@"stage"] isEqual:@"detail_visible"],@"Detail visibility is a distinct stage awaiting hidden timeline return");
    Event(@"repost_detail_confirmation_timeout",@{@"attempt":attempt});
    Check([Item(@"repost_detail")[@"stage"] isEqual:@"detail_visible"],@"A delayed timeout cannot erase already confirmed detail visibility");
    Event(@"repost_detail_return",@{@"hiddenPreserved":@YES,@"attempt":NSUUID.UUID.UUIDString,@"confirmed":@YES,@"observable":@YES});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"running"],@"A stale return from another attempt cannot complete the current navigation check");
    Event(@"repost_detail_visible",@{@"attempt":attempt,@"confirmed":@NO});
    Check([Item(@"repost_detail")[@"stage"] isEqual:@"detail_visible"],@"A later incomplete details callback cannot erase already matched details identity");
    Event(@"repost_detail_navigation",@{@"attempt":attempt,@"result":@"return_row_not_observable"});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"pending"] && [Item(@"repost_detail")[@"attempts"] isEqual:@1],@"Returning with an offscreen original row needs rechecking and does not increment attempts or invent a failure");
    Event(@"repost_detail_return",@{@"hiddenPreserved":@NO,@"attempt":attempt,@"confirmed":@YES,@"observable":@NO,@"result":@"return_row_not_observable"});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"pending"] && [Item(@"repost_detail")[@"stage"] isEqual:@"return_row_unavailable"] && [Item(@"repost_detail")[@"failureCount"] isEqual:@1],@"The actual unobservable return event is unknown evidence, not proof that the timeline expanded or a second failure");
    Event(@"repost_detail_return",@{@"hiddenPreserved":@YES,@"attempt":attempt,@"confirmed":@YES});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"pending"],@"Hidden-preserved alone cannot pass without explicit observable-row evidence");
    Event(@"repost_detail_return",@{@"hiddenPreserved":@YES,@"attempt":attempt,@"confirmed":@NO,@"observable":@YES});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"pending"],@"A hidden row without a confirmed return cannot automatically pass navigation");
    Event(@"repost_detail_return",@{@"attempt":attempt,@"confirmed":@YES,@"observable":@YES});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"pending"],@"An observable return with no hidden-state result cannot become a fabricated failure");
    Event(@"repost_detail_return",@{@"hiddenPreserved":@YES,@"attempt":attempt,@"confirmed":@YES,@"observable":@YES});
    Check([Item(@"repost_detail")[@"status"] isEqual:@"success"],@"Observed detail plus hidden return confirms the navigation cycle");
    Event(@"performance_started",@{});
    Event(@"performance_sample",@{@"visibleSeconds":@600,@"frameIntervals":@30000,@"slowIntervalRatio":@0.01,@"maxIntervalMs":@42,@"currentFootprintMB":@200,@"memoryWarnings":@0});
    Check([Item(@"performance")[@"status"] isEqual:@"running"] && [Item(@"performance")[@"observedSeconds"] isEqual:@600],@"Long sample duration never automatically proves a person's real usage experience");
    Event(@"performance_finished",@{@"visibleSeconds":@600});
    Check(![Item(@"performance")[@"running"] boolValue] && [Item(@"performance")[@"stage"] isEqual:@"sampling_finished"],@"Stopped sampling is shown as observed evidence awaiting user confirmation rather than still running");
    BHRDAcceptanceRecordManualResult(@"performance",YES);
    Check([Item(@"performance")[@"stage"] isEqual:@"user_confirmed"] && [Item(@"performance")[@"manualConfirmed"] boolValue],@"User confirmation is explicitly labelled and distinct from sampling");
    Event(@"performance_memory_warning",@{@"memoryMB":@280,@"peakMemoryMB":@300});
    Check([Item(@"performance")[@"status"] isEqual:@"failed"],@"New concrete memory warning remains visible even after manual confirmation");
    Event(@"performance_sample",@{@"memoryWarnings":@0});
    Check([Item(@"performance")[@"status"] isEqual:@"failed"],@"A later clean sample does not erase concrete warning evidence");
    Event(@"acceptance_export",@{@"phase":@"generated"}); Event(@"acceptance_export",@{@"phase":@"presented"});
    Check([Item(@"log_export")[@"status"] isEqual:@"running"],@"Opening a share sheet never counts as delivery or export completion");
    Event(@"acceptance_export",@{@"phase":@"completed"}); Event(@"acceptance_export",@{@"phase":@"cancelled"});
    Check([Item(@"log_export")[@"status"] isEqual:@"success"] && [Item(@"log_export")[@"lastOutcome"] isEqual:@"cancelled"],@"Later share cancellation retains system completion evidence without claiming recipient delivery");
    NSUInteger before=[BHRDAcceptanceSnapshot()[@"observationCount"] unsignedIntegerValue];
    Event(@"performance_private-user",@{@"profile":@"private-user"});
    Check([BHRDAcceptanceSnapshot()[@"observationCount"] unsignedIntegerValue]==before,@"Unknown events are ignored even when they resemble supported event families");
    NSError *error=nil; NSURL *report=BHRDAcceptanceExportReport(&error);
    NSString *json=[NSString stringWithContentsOfURL:report encoding:NSUTF8StringEncoding error:&error];
    Check(report && json.length && !error,@"A report can be exported from real session state");
    Check(![json containsString:@"private-user"] && ![json containsString:@"secret.invalid"] && ![json containsString:@"secret-post"],@"Account identifiers, URLs, errors' free text, and unknown fields never enter the acceptance export");
    Check(([[NSFileManager.defaultManager attributesOfItemAtPath:report.path error:NULL][NSFilePosixPermissions] unsignedIntegerValue]&0777)==0600,@"Export is private to the app's user");
    BHRDAcceptanceRemoveExport(report); Check(![NSFileManager.defaultManager fileExistsAtPath:report.path],@"Completed share artifacts can be cleaned up safely");
    BHRDAcceptanceBeginSession();
    Event(@"photo_save_result",@{@"success":@YES,@"acceptanceSession":sessionID});
    Check([Item(@"photo_save")[@"status"] isEqual:@"pending"],@"Late callback from an older acceptance session never contaminates a new session");
    Event(@"photo_save_start",@{}); Event(@"photo_save_committed",@{});
    BHRDAcceptanceTestReload(); BHRDAcceptanceObserveLaunch(NO,YES); BHRDAcceptanceFlush();
    Check([Item(@"photo_save")[@"status"] isEqual:@"pending"] && [Item(@"photo_save")[@"lastOutcome"] isEqual:@"interrupted"],@"Process restart during Photos submission records an unknown result rather than claiming failure, cancellation, or success");
    Check(![BHRDAcceptanceCurrentSessionIdentifier() isEqual:sessionID],@"Explicitly started sessions have unique identifiers");
    NSString *statePath=[NSProcessInfo.processInfo.environment[@"BHRD_ACCEPTANCE_TEST_DIR"] stringByAppendingPathComponent:@"acceptance.json"];
    NSMutableDictionary *stored=[[NSJSONSerialization JSONObjectWithData:[NSData dataWithContentsOfFile:statePath] options:NSJSONReadingMutableContainers error:NULL] mutableCopy];
    stored[@"private-user"]=@"https://secret.invalid/account";
    stored[@"environment"]=@{@"appVersion":@"private-user",@"os":@"private-user",@"account":@"private-user"};
    stored[@"observationCount"]=NSNull.null;
    NSMutableDictionary *badItem=stored[@"items"][0];
    badItem[@"title"]=@"private-user"; badItem[@"status"]=@"success"; badItem[@"stage"]=@"permission_granted";
    badItem[@"detail"]=@"https://secret.invalid/account"; badItem[@"successCount"]=@"private-user";
    badItem[@"attempts"]=@-12; badItem[@"cancelledCount"]=@1000001; badItem[@"failureCount"]=NSNull.null;
    badItem[@"manualConfirmed"]=@"private-user"; badItem[@"pendingAttempt"]=@"private-user";
    badItem[@"error"]=@[@"private-user"]; badItem[@"private-user"]=@"private-user";
    stored[@"events"]=@[@{@"event":@"repost_detail_return",@"time":@"private-user",@"observable":@NO,@"errorDomain":@"private-user",@"errorCode":NSNull.null,@"phase":@"private-user",@"account":@"private-user"},
        @{@"event":@"private-user",@"time":@1},NSNull.null,@[@"private-user"]];
    stored[@"launches"]=@[@{@"processID":NSUUID.UUID.UUIDString,@"time":@"private-user",@"paused":@NO,@"hooksEnabled":@YES,@"private-user":@"private-user"},
        @{@"processID":NSUUID.UUID.UUIDString,@"paused":NSNull.null,@"hooksEnabled":@YES},@"private-user"];
    stored[@"storageError"]=@{@"domain":@"private-user",@"code":@"private-user",@"message":@"private-user"};
    [[NSJSONSerialization dataWithJSONObject:stored options:0 error:NULL] writeToFile:statePath atomically:YES];
    BHRDAcceptanceTestReload(); NSDictionary *clean=BHRDAcceptanceSnapshot();
    Check([clean[@"mode"] isEqual:@"session"] && [clean[@"sessionID"] isEqual:stored[@"sessionID"]],@"Malformed optional saved fields cannot break a valid same-build session");
    Check([Item(@"photo_permission")[@"status"] isEqual:@"pending"] && [Item(@"photo_permission")[@"attempts"] isEqual:@0] && [Item(@"photo_permission")[@"cancelledCount"] isEqual:@1000000],@"Reload clamps malformed counts and rejects a success claim with no valid success evidence");
    Check(!Item(@"photo_permission")[@"pendingAttempt"] && ![Item(@"photo_permission")[@"manualConfirmed"] boolValue],@"Malformed persisted UUIDs and booleans never become current observations");
    Check([clean[@"events"] count]==1 && [clean[@"launches"] count]==1 && [clean[@"events"][0][@"errorDomain"] isEqual:@"redacted"],@"Reload reconstructs only known event and launch shapes, including sanitized error domains");
    report=BHRDAcceptanceExportReport(&error); json=[NSString stringWithContentsOfURL:report encoding:NSUTF8StringEncoding error:&error];
    Check(json.length && ![json containsString:@"private-user"] && ![json containsString:@"secret.invalid"],@"Previously persisted private or unknown fields cannot leak through report export after a restart");
    BHRDAcceptanceRemoveExport(report);
    Event(@"photo_save_result",@{@"success":@NO,@"errorDomain":@"private-user",@"errorCode":@-1});
    Check([Item(@"photo_save")[@"error"][@"domain"] isEqual:@"redacted"],@"Unknown live error domains are redacted before persistence, as well as during reload");
    stored=[[NSJSONSerialization JSONObjectWithData:[NSData dataWithContentsOfFile:statePath] options:NSJSONReadingMutableContainers error:NULL] mutableCopy];
    stored[@"build"][@"commit"]=@"an-older-commit";
    [[NSJSONSerialization dataWithJSONObject:stored options:0 error:NULL] writeToFile:statePath atomically:YES];
    BHRDAcceptanceTestReload();
    Check([BHRDAcceptanceSnapshot()[@"mode"] isEqual:@"recent"] && [Item(@"photo_save")[@"status"] isEqual:@"pending"],@"A different source build starts a separate observation window and never inherits old success claims");
    stored[@"build"][@"commit"]=BHRD_BUILD_COMMIT; stored[@"build"][@"version"]=@"2.4.7-1";
    if ([stored[@"build"][@"version"] isEqual:BHRD_BUILD_VERSION]) stored[@"build"][@"version"]=@"2.4.6-999";
    [[NSJSONSerialization dataWithJSONObject:stored options:0 error:NULL] writeToFile:statePath atomically:YES]; BHRDAcceptanceTestReload();
    Check([BHRDAcceptanceSnapshot()[@"mode"] isEqual:@"recent"],@"A different package revision is isolated even when the source commit happens to match");
    stored[@"build"]=@[@"private-user"]; stored[@"items"]=NSNull.null;
    [[NSJSONSerialization dataWithJSONObject:stored options:0 error:NULL] writeToFile:statePath atomically:YES]; BHRDAcceptanceTestReload();
    Check([BHRDAcceptanceSnapshot()[@"mode"] isEqual:@"recent"],@"A malformed persisted root shape falls back safely to pending recent observations");
    NSLog(@"Acceptance checks passed: %lu",(unsigned long)Checks);
} return 0; }
